
run_cpt: True

update:
  predictors:
    raw_data: False
    locally_created_seasonal_files: False
    cpt_input_data: False
  predictands:
    raw_data: False
    only_last_year_chirps_daily_raw_data: False
    cutted_chirps_data: False
    interpolated_data: False
    cpt_input_data: False
  crc_sas_grid:
    points_in_land: False

training_period:
  fyr: 1991
  lyr: 2020

# Must be commented to run the current month
#target_season:
#  mons: ['Jun']  # ['Jan', 'Aug']  # Start month
#  tgts: ['Jul']  # ['Feb-Apr', 'Dec-Feb']  # Target period

# Also must be commented to run the current month
#forecast_data:
#  fyr: [2021]  # [2020, 2020]  # Forecast first year (year of monf, if target season are in next year, it will be adjusted automatically)
#  monf: ['Jun']  # ['Jan', 'Aug'] # Initialization month / First month
#  nfcsts: [1]  # [1, 1]  # Number of forecast years (1: [2020], 2: [2020,2021], 3: [2020,2021,2022])

# When this information is provided, the target season and forecast
# are created using this month and year instead of the current month
# Comment the following two lines to run the current month
# initial_month: 10
# initial_year: 2021

# OBS:
# Predictors can have two more attributes (fcst_name and hcst_name)
# Valid predictors variables are: "precip" and "tmp2m"
# Valid predictors data sources are: "iridl" for ecmwf models and "noaa" for cpc/noaa models
# Valid predictands variables are: "prcp" and "t2m"
# Valid predictands data sources are: "chirps", "er5-land" and "crcsas"
models:
  ecmwf:
    predictors:
      variables: [ 'precip', 'tmp2m' ]
      data_sources: [ 'iridl', 'iridl' ]
    predictands:
      variables: [ 'prcp', 't2m' ]
      data_sources: [ 'chirps', 'era5-land' ]
  nmme:
    predictors:
      variables: [ 'precip', 'tmp2m' ]
      data_sources: [ 'noaa', 'noaa' ]
    predictands:
      variables: [ 'prcp', 't2m' ]
      data_sources: [ 'chirps', 'era5-land' ]
#  ncar_ccsm4:
#    predictors:
#      variables: [ 'precip', 'tmp2m' ]
#      data_sources: [ 'noaa', 'noaa' ]
#    predictands:
#      variables: [ 'prcp', 't2m' ]
#      data_sources: [ 'chirps', 'era5-land' ]
  nasa:
    predictors:
      variables: [ 'precip' ]
      data_sources: [ 'noaa' ]
    predictands:
      variables: [ 'prcp' ]
      data_sources: [ 'chirps' ]
#  gfdl:
#    predictors:
#      variables: [ 'precip', 'tmp2m' ]
#      data_sources: [ 'noaa', 'noaa' ]
#    predictands:
#      variables: [ 'prcp', 't2m' ]
#      data_sources: [ 'chirps', 'era5-land' ]
#  cmc2:
#    predictors:
#      variables: [ 'precip', 'tmp2m' ]
#      data_sources: [ 'noaa', 'noaa' ]
#    predictands:
#      variables: [ 'prcp', 't2m' ]
#      data_sources: [ 'chirps', 'era5-land' ]
#  cmc1:
#    predictors:
#      variables: [ 'precip', 'tmp2m' ]
#      data_sources: [ 'noaa', 'noaa' ]
#    predictands:
#      variables: [ 'prcp', 't2m' ]
#      data_sources: [ 'chirps', 'era5-land' ]
#  cfsv2:
#    predictors:
#      variables: [ 'precip', 'tmp2m' ]
#      data_sources: [ 'noaa', 'noaa' ]
#    predictands:
#      variables: [ 'prcp', 't2m' ]
#      data_sources: [ 'chirps', 'era5-land' ]

spatial_domain:
  predictor:
    nla: -10  # Northernmost latitude
    sla: -60  # Southernmost latitude
    wlo: 270  # Westernmost longitude
    elo: 330  # Easternmost longitude
  predictand:
    nla: -10  # Northernmost latitude
    sla: -52  # Southernmost latitude
    wlo: -78  # Westernmost longitude
    elo: -36  # Easternmost longitude
  crc_sas_grid:
    nla: -10.25  # Northernmost latitude
    sla: -56.25  # Southernmost latitude
    wlo: -78.75  # Westernmost longitude
    elo: -35.75  # Easternmost longitude
  plot:
    nla: -10  # Northernmost latitude
    sla: -60  # Southernmost latitude
    wlo: -78  # Westernmost longitude
    elo: -34.10  # Easternmost longitude

url:
  predictor:
    nmme:
      # trgt_type: "monthly" or "seasonal", file_type: "hindcast" or "forecast"
      # OBS: NO ESTAN EN FORMATO CPT, DEBEN RE-FORMATEARSE ANTES DE SER UTILIZADOS!!!
      template: "https://ftp.cpc.ncep.noaa.gov/International/nmme/${trgt_type}_nmme_${file_type}_in_cpt_format/${file_name}"
    ecmwf:
      template:
        # variable: variable to be downloaded (t2m or prcp)
        # unit: unit to be downloaded (mm/day for prcp, and Celsius_scale for t2m)
        # init_month_str: initialization month, last_year: last year with data Ej: 2021, 2022,
        # first_trgt_month: first target month, last_trgt_month: last target month, nla-sla-wlo-elo: predictor spatial domain
        # OBS: NO REQUIEREN MODIFICACIÓN, SE DESCARGAN Y SE USAN!!!
        monthly: "http://iridl.ldeo.columbia.edu/SOURCES/.EU/.Copernicus/.CDS/.C3S/.ECMWF/.SEAS5/.hindcast/.${variable}/S/(0000 1 ${init_month_str} 1981-2016)VALUES/M/1/25/RANGE[M]average/SOURCES/.EU/.Copernicus/.CDS/.C3S/.ECMWF/.SEAS5/.forecast/.${variable}/S/(0000 1 ${init_month_str} 2017-${last_year})VALUES/M/1/51/RANGE[M]average/appendstream/L/(${months_after_init_month_t1}.5)VALUES/Y/(${nla})(${sla})RANGEEDGES/X/(${wlo})(${elo})RANGEEDGES/(${unit})/unitconvert/-999/setmissing_value/[X/Y][S/L/add]cptv10.tsv"
        seasonal: "http://iridl.ldeo.columbia.edu/SOURCES/.EU/.Copernicus/.CDS/.C3S/.ECMWF/.SEAS5/.hindcast/.${variable}/S/(0000 1 ${init_month_str} 1981-2016)VALUES/M/1/25/RANGE[M]average/SOURCES/.EU/.Copernicus/.CDS/.C3S/.ECMWF/.SEAS5/.forecast/.${variable}/S/(0000 1 ${init_month_str} 2017-${last_year})VALUES/M/1/51/RANGE[M]average/appendstream/L/${months_after_init_month_t1}.5/${months_after_init_month_t2}.5/RANGE[L]//keepgrids/average/Y/(${nla})(${sla})RANGEEDGES/X/(${wlo})(${elo})RANGEEDGES/(${unit})/unitconvert/-999/setmissing_value/[X/Y][S/L/add]cptv10.tsv"
  predictand:
    chirps:
      type: "daily"
      monthly: "https://data.chc.ucsb.edu/products/CHIRPS-2.0/global_monthly/netcdf/chirps-v2.0.monthly.nc"
      daily: "https://data.chc.ucsb.edu/products/CHIRPS-2.0/global_daily/netcdf/p25/chirps-v2.0.${year}.days_p25.nc"
    crcsas:
      api: "https://api.crc-sas.org/ws-api"

folders:
  raw_data:
    hindcasts: "./input/raw_data/hindcasts/"
    forecasts: "./input/raw_data/forecasts/"
    chirps: "./input/raw_data/chirps/"
    era5_land: "./input/raw_data/era5_land/"
    crcsas: "./input/raw_data/crcsas/"
    shapefiles: "./input/raw_data/shapefiles/"
    images: "./input/raw_data/images/"
  predictors: "./input/predictors/"
  predictands: "./input/predictands/"
  crc_sas_grid: "./input/crc_sas_grid/"
  output: "./output/"
  plots: "./plots/"

files:
  plot_yaml: 'plot.yaml'  # This file is used to report the output files to the script that make plots!
  crc_sas_grid: 'points_in_land.shp'  # This file is created automatically, so, this is just the filename for it!!
  land_bound_shp: 'CRC_SAS.shp'  # It must be in folder.raw_data.shapefiles. It's used to identify points in land bound!
