
run_cpt: True

update:
  predictors:
    raw_data: False
    locally_created_seasonal_files: False
    cpt_input_data: True
  predictands:
    raw_data: False
    cutted_chirps_data: False
    interpolated_data: False
    cpt_input_data: True
  crc_sas_grid:
    points_in_land: False

target_season:
  mons: 'Jan'  # Start month
  tgts: 'Feb-Apr'  # Target period

forecast_data:
  fyr: 2020  # Forecast first year (year of monf, if target season are in next year, it will be adjusted automatically)
  monf: 'Jan'  # Initialization month / First month
  nfcsts: 1  # Number of forecast years (1: [2020], 2: [2020,2021], 3: [2020,2021,2022])

models:
  nmme:
    predictors: [ 'precip', 'tmp2m' ]
    predictands:
      variables: [ 'prcp', 't2m' ]
      data_sources: [ 'chirps', 'era5-land' ]
#  ncar_ccsm4:
#    predictors: [ 'precip', 'tmp2m' ]
#    predictands:
#      variables: [ 'prcp', 't2m' ]
#      data_sources: [ 'chirps', 'era5-land' ]
#  nasa:
#    predictors: [ 'precip' ]
#    predictands:
#      variables: [ 'prcp' ]
#      data_sources: [ 'chirps' ]
#  gfdl:
#    fcsf_name: 'gfdl_spear'
#    predictors: [ 'precip', 'tmp2m' ]
#    predictands:
#      variables: [ 'prcp', 't2m' ]
#      data_sources: [ 'chirps', 'era5-land' ]
#  cmc2:
#    predictors: [ 'precip', 'tmp2m' ]
#    predictands:
#      variables: [ 'prcp', 't2m' ]
#      data_sources: [ 'chirps', 'era5-land' ]
#  cmc1:
#    predictors: [ 'precip', 'tmp2m' ]
#    predictands:
#      variables: [ 'prcp', 't2m' ]
#      data_sources: [ 'chirps', 'era5-land' ]
#  cfsv2:
#    predictors: [ 'precip', 'tmp2m' ]
#    predictands:
#      variables: [ 'prcp', 't2m' ]
#      data_sources: [ 'chirps', 'era5-land' ]

spatial_domain:
  predictor:
    nla: -10  # Northernmost latitude
    sla: -60  # Southernmost latitude
    wlo: 270  # Westernmost longitude
    elo: 330  # Easternmost longitude
  predictand:
    nla: -10  # Northernmost latitude
    sla: -52  # Southernmost latitude
    wlo: -78  # Westernmost longitude
    elo: -36  # Easternmost longitude
  crc_sas_grid:
    nla: -10.25  # Northernmost latitude
    sla: -56.25  # Southernmost latitude
    wlo: -78.75  # Westernmost longitude
    elo: -35.75  # Easternmost longitude

url:
  predictor:
    # trgt_type: "monthly" or "seasonal", file_type: "hindcast" or "forecast"
    template: "https://ftp.cpc.ncep.noaa.gov/International/nmme/${trgt_type}_nmme_${file_type}_in_cpt_format/${file_name}"
  predictand:
    chirps: "https://data.chc.ucsb.edu/products/CHIRPS-2.0/global_monthly/netcdf/chirps-v2.0.monthly.nc"

folders:
  raw_data:
    hindcasts: "./input/raw_data/hindcasts/"
    forecasts: "./input/raw_data/forecasts/"
    chirps: "./input/raw_data/chirps/"
    era5_land: "./input/raw_data/era5_land/"
    shapefiles: "./input/raw_data/shapefiles/"
  predictors: "./input/predictors/"
  predictands: "./input/predictands/"
  crc_sas_grid: "./input/crc_sas_grid/"
  output: "./output/"

files:
  crc_sas_grid: 'points_in_land.shp'  # This file is created automatically, so, this is just the filename for it!!
  land_bound_shp: 'CRC_SAS.shp'  # It must be in folder.raw_data.shapefiles. It's used to identify points in land bound!
