
##################################################################
##                           README                             ##
##################################################################
## Este Dockerfile permite crear un contendor con todos los pa- ##
## quetes y todas las configuraciones necesarias para calibrar  ##
## pronósticos utilizando CPT desde python (PyCPT).             ##
##################################################################



##########################
## Set GLOBAL arguments ##
##########################

# Set CPT version
ARG CPT_VERSION="15.7.11"

# Set CPT HOME
ARG CPT_HOME="/opt/CPT"

# Set python version
ARG PYTHON_VERSION="3.10"

# Set PyCPT HOME
ARG PyCPT_HOME="/opt/pyCPT"

# Set user name and id
ARG USR_NAME="nonroot"
ARG USER_UID="1000"

# Set group name and id
ARG GRP_NAME="nonroot"
ARG USER_GID="1000"

# Set users passwords
ARG ROOT_PWD="root"
ARG USER_PWD=$USR_NAME

# Set Pycharm version
ARG PYCHARM_VERSION="2023.1"

# Set global CRON args
ARG CRON_TIME_STR="0 0 16 * *"


##########################
## Stage 1: Compile CPT ##
##########################

# Create image
FROM debian:bullseye-slim AS cpt_builder

# Set environment variables
ARG DEBIAN_FRONTEND=noninteractive

# Renew CPT ARGs
ARG CPT_VERSION
ARG CPT_HOME

# Install OS packages
RUN apt-get -y -qq update && \
    apt-get -y -qq upgrade && \
    apt-get -y -qq --no-install-recommends install \
        build-essential \
        # GCC5.x
        gcc make git \
        # GFortran
        gfortran \
        # wget
        ca-certificates wget \
        # to install ncdf4
        libnetcdf-dev && \
    rm -rf /var/lib/apt/lists/*

# Create CPT directory
RUN mkdir $CPT_HOME

# Download CPT
# version 15.6.3
#   web: https://academiccommons.columbia.edu/doi/10.7916/D8DJ6NDS
#   download link: https://academiccommons.columbia.edu/doi/10.7916/D88S5WQH/download
RUN wget --directory-prefix=/tmp/ --content-disposition \
    https://academiccommons.columbia.edu/doi/10.7916/D88S5WQH/download
# version 15.7.11
#   web: https://academiccommons.columbia.edu/doi/10.7916/d8-kb0s-2816
#   download link: https://academiccommons.columbia.edu/doi/10.7916/d8-enx1-j159/download
RUN wget --directory-prefix=/tmp/ --content-disposition \
    https://academiccommons.columbia.edu/doi/10.7916/d8-enx1-j159/download
# version 16.5.8
#   web: https://academiccommons.columbia.edu/doi/10.7916/d8-em5q-0f07
#   download link: https://academiccommons.columbia.edu/doi/10.7916/d8-6r1c-6146/download
RUN wget --directory-prefix=/tmp/ --content-disposition \
    https://academiccommons.columbia.edu/doi/10.7916/d8-6r1c-6146/download
# version 17.3.1
#   web: https://academiccommons.columbia.edu/doi/10.7916/d8-eepd-fm34
#   downloas link: https://academiccommons.columbia.edu/doi/10.7916/d8-ax2z-d749/download
RUN wget --directory-prefix=/tmp/ --content-disposition \
    https://academiccommons.columbia.edu/doi/10.7916/d8-ax2z-d749/download

# Extraer CPT.15.6.3.tar.gz
RUN tar -xzf /tmp/CPT.15.6.3.tar.gz -C /tmp
# Extraer CPT.15.7.11.tar.gz
RUN tar -xzf /tmp/CPT.15.7.11.tar.gz -C /tmp
# Extraer CPT.16.5.8.tar.gz
RUN tar -xzf /tmp/CPT.16.5.8.tar.gz -C /tmp
# Extraer CPT.17.3.1.tar.gz
RUN tar -xzf /tmp/CPT.17.3.1.tar.gz -C /tmp

# Mover código versión 15.6.3 a src
RUN mkdir $CPT_HOME/15.6.3
RUN mkdir $CPT_HOME/15.6.3/src
RUN mv /tmp/CPT/15.6.3/* $CPT_HOME/15.6.3/src/
# Mover código versión 15.7.11 a src
RUN mkdir $CPT_HOME/15.7.11
RUN mkdir $CPT_HOME/15.7.11/src
RUN mv /tmp/CPT/15.7.11/* $CPT_HOME/15.7.11/src/
# Mover código versión 16.5.8 a src
RUN mkdir $CPT_HOME/16.5.8
RUN mkdir $CPT_HOME/16.5.8/src
RUN mv /tmp/CPT/16.5.8/* $CPT_HOME/16.5.8/src/
# Mover código versión 17.3.1 a src
RUN mkdir $CPT_HOME/17.3.1
RUN mkdir $CPT_HOME/17.3.1/src
RUN mv /tmp/CPT/17.3.1/* $CPT_HOME/17.3.1/src/

# Instalar versión 15.6.3
# Acceder al código fuente
WORKDIR $CPT_HOME/15.6.3/src
# Para poder usar gfortran 10
RUN sed -i "s/-frecursive/-frecursive -fallow-argument-mismatch/g" ./lapack/lapack/make.inc
# Compilar e instalar CPT
RUN make distclean
RUN make
RUN make INSTALL_DIR=$CPT_HOME/15.6.3/ install

# Instalar versión 15.7.11
# Acceder al código fuente
WORKDIR $CPT_HOME/15.7.11/src
# Para poder usar gfortran 10
RUN sed -i "s/-frecursive/-frecursive -fallow-argument-mismatch/g" ./lapack/lapack/make.inc
# Compilar e instalar CPT
RUN make distclean
RUN make
RUN make INSTALL_DIR=$CPT_HOME/15.7.11/ install

# Instalar versión 16.5.8
# Acceder al código fuente
WORKDIR $CPT_HOME/16.5.8/src
# Compilar es instalar CPT
RUN make distclean
RUN make
RUN make INSTALL_DIR=$CPT_HOME/16.5.8/ install

# Instalar versión 17.3.1
# Acceder al código fuente
WORKDIR $CPT_HOME/17.3.1/src
# Compilar es instalar CPT
RUN make distclean
RUN make
RUN make INSTALL_DIR=$CPT_HOME/17.3.1/ install

# Configurar version por defecto para CPT
RUN echo "export CPT_BIN_DIR=$CPT_HOME/$CPT_VERSION/bin" >> /root/.bashrc
RUN echo "export PATH=$CPT_HOME/$CPT_VERSION/bin:$PATH" >> /root/.bashrc



######################################
## Stage 2: Install Python packages ##
######################################

# Create image
FROM python:${PYTHON_VERSION}-slim-bullseye AS py_builder

# Set environment variables
ARG DEBIAN_FRONTEND=noninteractive

# Set python environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install OS packages
RUN apt-get -y -qq update && \
    apt-get -y -qq upgrade && \
    apt-get -y -qq --no-install-recommends install \
        build-essential \
        # to install cartopy
        proj-bin libproj-dev libgeos-dev \
        # to install rpy2
        r-base r-base-dev && \
    rm -rf /var/lib/apt/lists/*

# Set work directory
WORKDIR /usr/src/app

# Upgrade pip and install dependencies
COPY requirements.txt /tmp/requirements.txt
RUN python3 -m pip install --upgrade pip && \
    python3 -m pip wheel --no-cache-dir --no-deps \
    --wheel-dir /usr/src/app/wheels -r /tmp/requirements.txt



#################################
## Stage 3: Install R packages ##
#################################

# Create image
FROM python:${PYTHON_VERSION}-slim-bullseye AS r_builder

# set environment variables
ARG DEBIAN_FRONTEND=noninteractive

# install OS packages
RUN apt-get -y -qq update && \
    apt-get -y -qq upgrade && \
    apt-get -y -qq --no-install-recommends install \
        build-essential \
        # install R
        r-base \
        # to install ncdf4
        libnetcdf-dev \
        # to install terra, a dependency of raster
        libgdal-dev && \
    rm -rf /var/lib/apt/lists/*

# set CRAN mirror
ARG CRAN_MIRROR="getOption('repos')"

# Install R package terra from a different cran mirror. Raster package requires terra and installs it in the background,
# but the installation of terra fails when it is installed from a repository other than https://rspatial.r-universe.dev.
# Rcpp is a dependency of terra package, but it is not installed automatically in the background when terra is installed.
RUN R -e "options(warn=2); install.packages('Rcpp', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')" \
 && R -e "options(warn=2); install.packages('terra', repos='https://rspatial.r-universe.dev', verbose=T, quiet=T, keep_outputs='/tmp/')"

# install R packages
RUN R -e "options(warn=2); install.packages('ncdf4', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('raster', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('dplyr', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('tibble', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"



#########################################
## Stage 4: Copy installation folders  ##
#########################################

# Create PyCPT image
FROM python:${PYTHON_VERSION}-slim-bullseye AS cpt-py-r_final

# Set environment variables
ARG DEBIAN_FRONTEND=noninteractive

# Renew CPT ARGs
ARG CPT_VERSION
ARG CPT_HOME

# Renew PyCPT_HOME
ARG PyCPT_HOME

# Install OS packages
RUN apt-get -y -qq update && \
    apt-get -y -qq upgrade && \
    apt-get -y -qq --no-install-recommends install \
        # install R
        r-base \
        # to be able to use cartopy (Python)
        proj-bin libproj-dev libgeos-dev \
        # to be able to use rpy2 (R-Python)
        libblas-dev \
        # to be able to use ncdf4 (R)
        libnetcdf-dev \
        # to be able to use terra, a dependency of raster (R)
        libgdal-dev && \
    rm -rf /var/lib/apt/lists/*

# Copy CPT executable from cpt_builder
COPY --from=cpt_builder $CPT_HOME/$CPT_VERSION $CPT_HOME

# Setup CPT for root
RUN echo "export CPT_BIN_DIR=$CPT_HOME/bin" >> /root/.bashrc
RUN echo "export PATH=$CPT_HOME/bin:$PATH" >> /root/.bashrc

# Install python dependencies from py_builder
COPY --from=py_builder /usr/src/app/wheels /wheels
RUN python3 -m pip install --upgrade pip && \
    python3 -m pip install --no-cache /wheels/* && \
    rm -rf /wheels

# Install R packages from r_builder
# https://forums.docker.com/t/using-multi-stage-docker-build-for-slimming-down-images-with-r-dependency/67967
RUN mkdir -p /usr/lib/R \
             /usr/local/lib/R/site-library
COPY --from=r_builder /usr/bin/R /usr/bin/R
COPY --from=r_builder /usr/bin/Rscript /usr/bin/Rscript
COPY --from=r_builder /usr/lib/R /usr/lib/R
COPY --from=r_builder /usr/local/lib/R/site-library /usr/local/lib/R/site-library
COPY --from=r_builder /tmp /tmp

# Set R libs paths (see: https://stat.ethz.ch/R-manual/R-devel/library/base/html/libPaths.html)
ENV R_LIBS="/usr/lib/R/library"
ENV R_LIBS_USER="/usr/local/lib/R/site-library"
ENV R_LIBS_SITE="/usr/local/lib/R/site-library"



#################################
## Stage 5: Create PyCPT image ##
#################################

# Create PyCPT image
FROM cpt-py-r_final AS pycpt_builder

# Set environment variables
ARG DEBIAN_FRONTEND=noninteractive

# Renew PyCPT_HOME
ARG PyCPT_HOME

# Create PyCPT_HOME folder
RUN mkdir -p $PyCPT_HOME

# Copy PyCPT code
COPY *.py $PyCPT_HOME/
COPY *.yaml $PyCPT_HOME/

# Create input and output folders (these folders are too big so they must be used them as volumes)
RUN mkdir -p $PyCPT_HOME/input
RUN mkdir -p $PyCPT_HOME/output



###########################################
## Stage 6: Install management packages  ##
###########################################

# Create image
FROM pycpt_builder AS pytcpt_mgmt

# Set environment variables
ARG DEBIAN_FRONTEND=noninteractive

# Install OS packages
RUN apt-get -y -qq update && \
    apt-get -y -qq upgrade && \
    apt-get -y -qq --no-install-recommends install \
        # install Tini (https://github.com/krallin/tini#using-tini)
        tini \
        # to see process with pid 1
        htop procps \
        # to allow edit files
        vim \
        # to run process with cron
        cron && \
    rm -rf /var/lib/apt/lists/*

# Setup cron to allow it run as a non root user
RUN chmod u+s $(which cron)

# Add Tini (https://github.com/krallin/tini#using-tini)
ENTRYPOINT ["/usr/bin/tini", "-g", "--"]



######################################
## Stage 7: Setup PyCPT core image  ##
######################################

# Create image
FROM pytcpt_mgmt AS pycpt-core

# Set environment variables
ARG DEBIAN_FRONTEND=noninteractive

# Renew PyCPT_HOME
ARG PyCPT_HOME

# Renew CRON ARGs
ARG CRON_TIME_STR

# Set environment variables
ENV CRON_TIME_STR=${CRON_TIME_STR}

# Crear archivo de configuración de CRON
RUN printf "\n\
# Setup cron to run files processor \n\
${CRON_TIME_STR} /usr/local/bin/python ${PyCPT_HOME}/main.py >> /proc/1/fd/1 2>> /proc/1/fd/1\n\
\n" > ${PyCPT_HOME}/crontab.txt
RUN chmod a+rw ${PyCPT_HOME}/crontab.txt

# Setup CRON for root user
RUN (cat ${PyCPT_HOME}/crontab.txt) | crontab -

# Crear script de inicio.
RUN printf "#!/bin/bash \n\
set -e \n\
\n\
# Reemplazar tiempo ejecución automática del procesador de archivos \n\
crontab -l | sed \"/main.py/ s|^\S* \S* \S* \S* \S*|\$CRON_TIME_STR|g\" | crontab - \n\
\n\
# Ejecutar cron \n\
cron -fL 15 \n\
\n" > /startup.sh
RUN chmod a+x /startup.sh

# Create script to check container health
RUN printf "#!/bin/bash\n\
if [ \$(ls /tmp/pycpt.pid 2>/dev/null | wc -l) != 0 ] && \n\
   [ \$(ps -ef | grep 'main.py' | grep -v 'grep' | wc -l) == 0 ] \n\
then \n\
  exit 1 \n\
else \n\
  exit 0 \n\
fi \n\
\n" > /check-healthy.sh
RUN chmod a+x /check-healthy.sh

# Run your program under Tini (https://github.com/krallin/tini#using-tini)
CMD [ "bash", "-c", "/startup.sh" ]
# or docker run your-image /your/program ...

# Verificar si hubo alguna falla en la ejecución del replicador
HEALTHCHECK --interval=3s --timeout=3s --retries=3 CMD bash /check-healthy.sh



###################################
## Stage 8: Create non-root user ##
###################################

# Create image
FROM pycpt-core AS pycpt_nonroot_builder

# Set environment variables
ARG DEBIAN_FRONTEND=noninteractive

# Renew USER ARGs
ARG USR_NAME
ARG USER_UID
ARG GRP_NAME
ARG USER_GID
ARG ROOT_PWD
ARG USER_PWD

# Install OS packages
RUN apt-get -y -qq update && \
    apt-get -y -qq upgrade && \
    apt-get -y -qq --no-install-recommends install \
        # to run sudo
        sudo && \
    rm -rf /var/lib/apt/lists/*

# Modify root password
RUN echo "root:$ROOT_PWD" | chpasswd

# Create a non-root user, so the container can run as non-root
# OBS: the UID and GID must be the same as the user that own the
# input and the output volumes, so there isn't perms problems!!
# Se recomienda crear usuarios en el contendor de esta manera,
# ver: https://nickjanetakis.com/blog/running-docker-containers-as-a-non-root-user-with-a-custom-uid-and-gid
# Se agregar --no-log-init para prevenir un problema de seguridad,
# ver: https://jtreminio.com/blog/running-docker-containers-as-current-host-user/
RUN groupadd --gid $USER_GID $GRP_NAME
RUN useradd --no-log-init --uid $USER_UID --gid $USER_GID --shell /bin/bash \
    --comment "Non-root User Account" --create-home $USR_NAME

# Modify the password of non-root user
RUN echo "$USR_NAME:$USER_PWD" | chpasswd

# Add non-root user to sudoers and to adm group
# The adm group was added to allow non-root user to see logs
RUN usermod -aG sudo $USR_NAME && \
    usermod -aG adm $USR_NAME

# To allow sudo without password
# RUN echo "$USR_NAME ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USR_NAME && \
#     chmod 0440 /etc/sudoers.d/$USR_NAME



############################################
## Stage 9.1: Install Pycharm (for debug) ##
############################################

# Create image
FROM pycpt_nonroot_builder AS pycpt-pycharm

# Become root
USER root

# Set environment variables
ARG DEBIAN_FRONTEND=noninteractive

# Renew PyCPT_HOME
ARG PyCPT_HOME

# Renew USER ARGs
ARG USR_NAME
ARG GRP_NAME

# Updata apt cache and install wget
RUN apt-get -y -qq update && \
    apt-get -y -qq upgrade && \
    apt-get -y -qq --no-install-recommends install \
        curl wget git

# Renew ARGs
ARG PYCHARM_VERSION

# Download Pycharm IDE
RUN wget https://download.jetbrains.com/python/pycharm-community-${PYCHARM_VERSION}.tar.gz -P /tmp/

# Install packages required to run PyCharm IDE
RUN count=$(ls /tmp/pycharm-*.tar.gz | wc -l) && [ $count = 1 ] \
    && apt-get -y -qq --no-install-recommends install \
        # Without this packages, PyCharm don't start
        libxrender1 libxtst6 libxi6 libfreetype6 fontconfig \
        # Without this packages, PyCharm start, but reports that they are missing
        libatk1.0-0 libatk-bridge2.0-0 libdrm-dev libxkbcommon-dev libdbus-1-3 \
        libxcomposite1 libxdamage1 libxfixes3 libxrandr-dev libgbm1 libasound2 \
        libcups2 libatspi2.0-0 libxshmfence1 \
        # Without this packages, PyCharm start, but shows errors when running
        procps libsecret-1-0 gnome-keyring libxss1 libxext6 firefox-esr \
        #libnss3 libxext-dev libnspr4 \
    || :  # para entender porque :, ver https://stackoverflow.com/a/49348392/5076110

# Install PyCharm IDE
RUN count=$(ls /tmp/pycharm-*.tar.gz | wc -l) && [ $count = 1 ] \
    && mkdir /opt/pycharm \
    && tar xzf /tmp/pycharm-*.tar.gz -C /opt/pycharm --strip-components 1 \
    && chown -R $USR_NAME:$GRP_NAME /opt/pycharm \
    || :  # para entender porque :, ver https://stackoverflow.com/a/49348392/5076110

# Renew ARGs
ARG PYTHON_VERSION

# Pycharm espera que los paquetes python estén en dist-packages, pero están en site-packages.
# Esto es así porque python no se instaló usando apt o apt-get, y cuando esto ocurre, la carpeta
# en la que se instalan los paquetes es site-packages y no dist-packages.
RUN mkdir -p /usr/local/lib/python${PYTHON_VERSION}/dist-packages \
    && ln -s /usr/local/lib/python${PYTHON_VERSION}/site-packages/* \
             /usr/local/lib/python${PYTHON_VERSION}/dist-packages/

# Change to non-root user
USER $USR_NAME

# Set work directory
WORKDIR $PyCPT_HOME

# Run pycharm under Tini (https://github.com/krallin/tini#using-tini)
CMD ["sh", "/opt/pycharm/bin/pycharm.sh", "-Dide.browser.jcef.enabled=false"]
# or docker run your-image /your/program ...


#
# Ejecución de pycharm:
#
# 1- docker volume create pycpt-home
#
# 2- export DOCKER_BUILDKIT=1
#
# 3- docker build --force-rm \
#      --target pycpt-pycharm \
#      --tag pycpt-pycharm:latest \
#      --build-arg USER_UID=$(stat -c "%u" .) \
#      --build-arg USER_GID=$(stat -c "%g" .) \
#      --file dockerfile-pycpt .
#
# 4- docker run -ti --rm \
#      --name pycpt-pycharm \
#      --env DISPLAY=$DISPLAY \
#      --volume /tmp/.X11-unix:/tmp/.X11-unix \
#      --volume pycpt-home:/home/nonroot \
#      --volume $(pwd):/opt/pyCPT \
#      --detach pycpt-pycharm:latest
#



##############################################
## Stage 9.2: Setup and run final APP image ##
##############################################

# Create image
FROM pycpt_nonroot_builder AS pycpt-nonroot

# Become root
USER root

# Renew CPT_HOME
ARG CPT_HOME

# Renew PyCPT_HOME
ARG PyCPT_HOME

# Renew USER ARGs
ARG USR_NAME
ARG USER_UID
ARG USER_GID

# Change files owner
RUN chown -R $USER_UID:$USER_GID $CPT_HOME
RUN chown -R $USER_UID:$USER_GID $PyCPT_HOME

# Setup cron to allow it run as a non root user
RUN chmod u+s $(which cron)

# Setup cron
RUN (cat $PyCPT_HOME/crontab.txt) | crontab -u $USR_NAME -

# Add Tini (https://github.com/krallin/tini#using-tini)
ENTRYPOINT ["/usr/bin/tini", "-g", "--"]

# Run your program under Tini (https://github.com/krallin/tini#using-tini)
CMD [ "bash", "-c", "/startup.sh" ]
# or docker run your-image /your/program ...

# Verificar si hubo alguna falla en la ejecución del replicador
HEALTHCHECK --interval=3s --timeout=3s --retries=3 CMD bash /check-healthy.sh

# Access non-root user directory
WORKDIR /home/$USR_NAME

# Switch back to non-root user to avoid accidental container runs as root
USER $USR_NAME


# Activar docker build kit
# export DOCKER_BUILDKIT=1

# CONSTRUIR IMAGEN (CORE)
# docker build --force-rm \
#   --target pycpt-core \
#   --tag ghcr.io/danielbonhaure/run-cpt:pycpt-core-v1.0 \
#   --build-arg CRON_TIME_STR="0 0 16 * *" \
#   --file dockerfile-pycpt .

# LEVANTAR IMAGEN A GHCR
# docker push ghcr.io/danielbonhaure/run-cpt:pycpt-core-v1.0

# CONSTRUIR IMAGEN (NON-ROOT)
# docker build --force-rm \
#   --target pycpt-nonroot \
#   --tag pycpt-nonroot:latest \
#   --build-arg USER_UID=$(stat -c "%u" .) \
#   --build-arg USER_GID=$(stat -c "%g" .) \
#   --build-arg CRON_TIME_STR="0 0 16 * *" \
#   --file dockerfile-pycpt .

# CORRER OPERACIONALMENTE CON CRON
# docker run --name pycpt \
#   --volume $(pwd)/input:/opt/pyCPT/input \
#   --volume $(pwd)/output:/opt/pyCPT/output \
#   --volume $(pwd)/plot.yaml:/opt/pyCPT/plot.yaml \  # no es necesario si se usa el nuevo graficador
#   --detach pycpt-nonroot:latest

# CORRER MANUALMENTE
# docker run --name pycpt \
#   --volume $(pwd)/input:/opt/pyCPT/input \
#   --volume $(pwd)/output:/opt/pyCPT/output \
#   --volume $(pwd)/config.yaml:/opt/pyCPT/config.yaml \
#   --volume $(pwd)/plot.yaml:/opt/pyCPT/plot.yaml \  # no es necesario si se usa el nuevo graficador
#   --rm pycpt-nonroot:latest python /opt/pyCPT/main.py --year 2023 --month 6
