
##################################################################
##                           README                             ##
##################################################################
## Este Dockerfile permite crear un contendor con todos los pa- ##
## quetes y todas las configuraciones necesarias para graficar  ##
## pronósticos calibrados utilizando CPT desde python (PyCPT).  ##
##################################################################



##########################
## Set GLOBAL arguments ##
##########################

# Set R version
ARG R_VERSION="4.1.2"

# Set rPLOT HOME
ARG rPLOT_HOME="/opt/rPLOT"

# Set global CRON args
ARG CRON_TIME_STR="0 0 17 * *"


#################################
## Stage 1: Install R packages ##
#################################

# Create image
FROM rocker/r-ver:${R_VERSION} AS r_builder

# Set environment variables
ARG DEBIAN_FRONTEND=noninteractive

# Install OS packages
RUN apt-get --quiet --assume-yes update && \
    apt-get --quiet --assume-yes upgrade && \
    apt-get --quiet --assume-yes --no-install-recommends install \
        build-essential \
        # to install ncdf4
        libnetcdf-dev \
        # to install terra, a dependency of raster
        libgdal-dev libgeos-dev libproj-dev \
        # to install classInt, a dependency of sf
        gfortran \
        # to install units, a dependency of sf
        libudunits2-dev \
        # to install systemfonts, a dependency of ggiraph
        libfontconfig1-dev && \
    rm -rf /var/lib/apt/lists/*

# Set CRAN mirror
ARG CRAN_MIRROR="getOption('repos')"

# Install R packages
RUN R -e "options(warn=2); install.packages('sp', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('ncdf4', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('terra', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('raster', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('dplyr', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('tibble', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('sf', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('stringr', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('tidyr', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('purrr', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('yaml', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('glue', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('lubridate', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('gstat', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('rasterVis', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('htmltools', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('leaflet', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('plainview', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('leafem', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('ggplot2', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('rnaturalearth', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('RColorBrewer', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('httr', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('jsonlite', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('lattice', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('leaflet.extras2', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('RCurl', verbose=T, repos=${CRAN_MIRROR}, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('rnaturalearthdata', repos=${CRAN_MIRROR}, verbose=T, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('ggiraph', verbose=T, repos=${CRAN_MIRROR}, quiet=T, keep_outputs='/tmp/')"
RUN R -e "options(warn=2); install.packages('rgdal', verbose=T, repos=${CRAN_MIRROR}, quiet=T, keep_outputs='/tmp/')"



##########################################
## Stage 2: Copy R installation folders ##
##########################################

# Create rPLOT image
FROM rocker/r-ver:${R_VERSION} AS r_final

# Set environment variables
ARG DEBIAN_FRONTEND=noninteractive

# Install OS packages
RUN apt-get --quiet --assume-yes update && \
    apt-get --quiet --assume-yes upgrade && \
    apt-get --quiet --assume-yes --no-install-recommends install \
        # to be able to use ncdf4 (R)
        libnetcdf-dev \
        # to install terra, a dependency of raster (R)
        libgdal-dev \
        # to be able to import and use units (R)
        libudunits2-dev \
        # to be able to use htmlwidgets (R)
        pandoc && \
    rm -rf /var/lib/apt/lists/*

# Install R packages from r_builder
# https://forums.docker.com/t/using-multi-stage-docker-build-for-slimming-down-images-with-r-dependency/67967
RUN mkdir -p /usr/local/lib/R \
             /usr/local/lib/R/site-library
COPY --from=r_builder /usr/local/bin/R /usr/local/bin/R
COPY --from=r_builder /usr/local/bin/Rscript /usr/local/bin/Rscript
COPY --from=r_builder /usr/local/lib/R /usr/local/lib/R
COPY --from=r_builder /usr/local/lib/R/site-library /usr/local/lib/R/site-library
COPY --from=r_builder /tmp /tmp

# Set R libs paths (see: https://stat.ethz.ch/R-manual/R-devel/library/base/html/libPaths.html)
ENV R_LIBS="/usr/local/lib/R/library"
ENV R_LIBS_USER="/usr/local/lib/R/site-library"
ENV R_LIBS_SITE="/usr/local/lib/R/site-library"



##########################################
## Stage 3: Install management packages ##
##########################################

# Create image
FROM r_final AS base_image

# Set environment variables
ARG DEBIAN_FRONTEND=noninteractive

# Install OS packages
RUN apt-get --quiet --assume-yes update && \
    apt-get --quiet --assume-yes --no-install-recommends install \
        # install Tini (https://github.com/krallin/tini#using-tini)
        tini \
        # to see process with pid 1
        htop procps \
        # to allow edit files
        vim \
        # to run process with cron
        cron && \
    rm -rf /var/lib/apt/lists/*

# Create utils directory
RUN mkdir -p /opt/utils

# Create script to load environment variables
RUN printf "#!/bin/bash \n\
export \$(cat /proc/1/environ | tr '\0' '\n' | xargs -0 -I {} echo \"{}\") \n\
\n" > /opt/utils/load-envvars

# Create startup/entrypoint script
RUN printf "#!/bin/bash \n\
set -e \n\
\043 https://docs.docker.com/reference/dockerfile/#entrypoint \n\
exec \"\$@\" \n\
\n" > /opt/utils/entrypoint

# Create script to check the container's health
RUN printf "#!/bin/bash \n\
exit 0 \n\
\n" > /opt/utils/check-healthy

# Set minimal permissions to the utils scripts
RUN chmod --recursive u=rx,g=rx,o=rx /opt/utils

# Allows utils scripts to run as a non-root user
RUN chmod u+s /opt/utils/load-envvars

# Setup cron to allow it to run as a non-root user
RUN chmod u+s $(which cron)

# Add Tini (https://github.com/krallin/tini#using-tini)
ENTRYPOINT ["/usr/bin/tini", "-g", "--"]



#################################
## Stage 4: Create rPLOT image ##
#################################

# Create EREG image
FROM base_image AS rplot_builder

# Set environment variables
ARG DEBIAN_FRONTEND=noninteractive

# Set rPLOT HOME
ARG rPLOT_HOME

# Create rPLOT_HOME folder
RUN mkdir -p ${rPLOT_HOME}

# Copy rPLOT code
COPY graficos_originales/*.R ${rPLOT_HOME}
COPY graficos_originales/plot.yaml ${rPLOT_HOME}/plot.yaml

# Create input and output folders (these folders are too big so they must be used them as volumes)
RUN mkdir -p ${rPLOT_HOME}/input
RUN mkdir -p ${rPLOT_HOME}/output
RUN mkdir -p ${rPLOT_HOME}/plots

# Save Git commit hash of this build into ${rPLOT_HOME}/repo_version.
# https://github.com/docker/hub-feedback/issues/600#issuecomment-475941394
# https://docs.docker.com/build/building/context/#keep-git-directory
COPY ./.git /tmp/git
RUN export head=$(cat /tmp/git/HEAD | cut -d' ' -f2) && \
    if echo "${head}" | grep -q "refs/heads"; then \
    export hash=$(cat /tmp/git/${head}); else export hash=${head}; fi && \
    echo "${hash}" > ${rPLOT_HOME}/repo_version && rm -rf /tmp/git

# Set permissions of app files
RUN chmod -R u=rw,g=rw,o=r ${rPLOT_HOME}



#####################################
## Stage 5: Setup rPLOT core image ##
#####################################

# Create image
FROM rplot_builder AS rplot_core

# Set environment variables
ARG DEBIAN_FRONTEND=noninteractive

# Renew ARGs
ARG rPLOT_HOME
ARG CRON_TIME_STR

# Create CRON configuration file
RUN printf "\n\
SHELL=/bin/bash \n\
BASH_ENV=/opt/utils/load-envvars \n\
\n\
\043 Setup cron to run files processor \n\
${CRON_TIME_STR} /usr/bin/Rscript ${rPLOT_HOME}/plot.R >> /proc/1/fd/1 2>> /proc/1/fd/1 #JOB_ID_1 \n\
\n" > ${PyCPT_HOME}/crontab.conf

# Create startup/entrypoint script
RUN printf "#!/bin/bash \n\
set -e \n\
\n\
\043 Reemplazar tiempo ejecución automática del procesador de archivos \n\
declare CRON_REGEX=\"^([[:graph:]]+[[:space:]]+){4}[[:graph:]]+\" \n\
sed -i -E \"/JOB_ID_1/ s|\${CRON_REGEX}|\${CRON_TIME_STR}|g\" ${PyCPT_HOME}/crontab.conf \n\
crontab -l | sed -E \"/JOB_ID_1/ s|\${CRON_REGEX}|\${CRON_TIME_STR}|g\" | crontab - \n\
\n\
exec \"\$@\" \n\
\n" > /opt/utils/entrypoint

# Create script to check the container's health
RUN printf "#!/bin/bash\n\
if [ \$(ls /tmp/plotR.pid 2>/dev/null | wc -l) != 0 ] && \n\
   [ \$(ps -ef | grep plot.R | wc -l) == 0 ] \n\
then \n\
  exit 1 \n\
else \n\
  exit 0 \n\
fi \n\
\n" > /opt/utils/check-healthy

# Set minimal permissions to the new scripts and files
RUN chmod u=rw,g=r,o=r ${rPLOT_HOME}/crontab.conf

# Set read-only environment variables
ENV rPLOT_HOME=${rPLOT_HOME}

# Set user-definable environment variables
ENV CRON_TIME_STR=${CRON_TIME_STR}



######################################
## Stage 6: Setup rPLOT final image ##
######################################

# Create image
FROM rplot_core AS rplot-root

# Set environment variables
ARG DEBIAN_FRONTEND=noninteractive

# Renew ARGs
ARG rPLOT_HOME

# Setup CRON for root user
RUN (cat ${rPLOT_HOME}/crontab.conf) | crontab -

# Create standard directories used for specific types of user-specific data, as defined 
# by the XDG Base Directory Specification. For when "docker run --user uid:gid" is used.
# OBS: don't forget to add --env HOME=/home when running the container.
RUN mkdir -p /home/.local/share && \
    mkdir -p /home/.cache && \
    mkdir -p /home/.config
# Set permissions, for when "docker run --user uid:gid" is used
RUN chmod -R a+rwx /home/.local /home/.cache /home/.config

# Add Tini (https://github.com/krallin/tini#using-tini)
ENTRYPOINT [ "/usr/bin/tini", "-g", "--", "/opt/utils/entrypoint" ]

# Run your program under Tini (https://github.com/krallin/tini#using-tini)
CMD [ "cron", "-fL", "15" ]
# or docker run your-image /your/program ...

# Configurar verificación de la salud del contenedor
HEALTHCHECK --interval=3s --timeout=3s --retries=3 CMD bash /opt/utils/check-healthy

# Set work directory
WORKDIR ${rPLOT_HOME}



#####################################################
## Usage: Commands to Build and Run this container ##
#####################################################


# CONSTRUIR IMAGEN (CORE)
# docker build --force-rm \
#   --target rplot-root \
#   --tag rplot-core:latest \
#   --build-arg CRON_TIME_STR="0 0 17 * *" \
#   --file Dockerfile.rplot ..

# CONSTRUIR IMAGEN (PYCHARM NON-ROOT)
# docker build \
#   --tag rplot-nonroot:latest \
#   --build-arg BASE_IMAGE="rplot-core:latest" \
#   --build-arg USER_UID=$(stat -c "%u" .) \
#   --build-arg USER_GID=$(stat -c "%g" .) \
#   --file Dockerfile.nonroot ..

# CORRER OPERACIONALMENTE CON CRON
# docker run --name pycpt-plt \
#   --mount type=bind,src=$(pwd)/input,dst=/opt/rPLOT/input \
#   --mount type=bind,src=$(pwd)/output,dst=/opt/rPLOT/output \
#   --mount type=bind,src=$(pwd)/plots,dst=/opt/rPLOT/plots \
#   --mount type=bind,src=$(pwd)/plot.yaml,dst=/opt/rPLOT/plot.yaml \
#   --detach rplot-nonroot:latest

# CORRER MANUALMENTE
# docker run --name pycpt-plt --rm \
#   --mount type=bind,src=$(pwd)/input,dst=/opt/rPLOT/input \
#   --mount type=bind,src=$(pwd)/output,dst=/opt/rPLOT/output \
#   --mount type=bind,src=$(pwd)/plots,dst=/opt/rPLOT/plots \
#   --mount type=bind,src=$(pwd)/plot.yaml,dst=/opt/rPLOT/plot.yaml \
#   --rm rplot-nonroot:latest Rscript /opt/rPLOT/plot.R
